### ISSUE TITLE
Task 3 - API status

### ISSUE THREAD

**Issue by yeungegs** [yeungegs/AirBnB_clone_v4#4]
- [x] Update the API entry point (api/v1/app.py) by replacing the current CORS CORS(app, origins="0.0.0.0") by CORS(app, resources={r"/api/v1/*": {"origins": "*"}}).
- [x] Change the route 1-hbnb to 2-hbnb in the file 2-hbnb.py (based on 1-hbnb.py)

Create a new template 2-hbnb.html (based on 1-hbnb.html) and update it:
- [x] Import the javascript static/scripts/2-hbnb.js in the <HEAD> tag (instead of 1-hbnb.js)
Add a new DIV element in the HEADER tag:
- [x] Attribute ID should be api_status
- [x] Align to the right
- [x] Circle of 40px diameter
- [x] Center vertically
- [x] At 30px of the right border
- [x] Background color #cccccc

- [x] Add a class available for this new element in web_dynamic/static/styles/3-header.css:
- [x] Background color #ff545f

Write a javascript script (static/scripts/2-hbnb.js):
- [x] Based on 1-hbnb.js
Request http://0.0.0.0:5001/api/v1/status/:
If in the status is "OK", add the class available to the DIV#api_status
Otherwise, remove the class available to the DIV#api_status

**Comment by spencerhcheng** [comment]
- [ ] Update the API entry point (api/v1/app.py) by replacing the current CORS CORS(app, origins="0.0.0.0") by CORS(app, resources={r"/api/v1/*": {"origins": "*"}}).
- [ ] Change the route 1-hbnb to 2-hbnb in the file 2-hbnb.py (based on 1-hbnb.py)

Create a new template 2-hbnb.html (based on 1-hbnb.html) and update it:
- [ ] Import the javascript static/scripts/2-hbnb.js in the <HEAD> tag (instead of 1-hbnb.js)
Add a new DIV element in the HEADER tag:
- [ ] Attribute ID should be api_status
- [ ] Align to the right
- [ ] Circle of 40px diameter
- [ ] Center vertically
- [ ] At 30px of the right border
- [ ] Background color #cccccc

- [ ] Add a class available for this new element in web_dynamic/static/styles/3-header.css:
- [ ] Background color #ff545f

Write a javascript script (static/scripts/2-hbnb.js):
- [ ] Based on 1-hbnb.js
Request http://0.0.0.0:5001/api/v1/status/:
If in the status is "OK", add the class available to the DIV#api_status
Otherwise, remove the class available to the DIV#api_status
